name: resources_generator
description: An resource class generator for Flutter, like Android resource class R.
version: 1.0.6
repository: https://github.com/anhquan7826/resources_generator

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

executables:
  generate:
  monitor:

environment:
  sdk: ^3.3.3

dependencies:
  collection: ^1.18.0
  path: ^1.9.0
  rxdart: ^0.28.0
  watcher: ^1.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
